### ISSUE TITLE
Don't display "target" dropdown in DeploymentDialog if not logged into any TAS instances

### ISSUE THREAD

**Issue by atwoosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#134]
... prompt log-in in that space instead?

**Comment by atwoosnam** [comment]
In order to complete this ticket (and bug #143), the existing architecture would require re-adding logic to keep the `TasExplorerViewModel.TasConnection` in sync with `CloudFoundryService.ConnectedCf`. This feels needlessly complex when there's a simpler design available (diagrammed above)

**Comment by zzori-theoriginal** [comment]
Here is the Deployment Window without the dropdown feature; it forces the user to log in instead of having an empty dropdown.
![deploydianodropdown.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/6c192a0a-2858-46f5-8096-9a13e0058d07)

Once the user is logged in, the next step will be to auto-populate the `Target` field in the Deployment Window
![deploydiaandtas.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/755599be-c5b7-42c0-ac7a-081fa82e2af8)

**Comment by colsonrice** [comment]
See design here: 
[0 2021-08-30 at 11.57.48 AM.pdf](https://github.com/vmware-tanzu/tanzu-toolkit-for-visual-studio/files/7122389/0.2021-08-30.at.11.57.48.AM.pdf)
