### ISSUE TITLE
Validate existence of services when a manifest is imported

### ISSUE THREAD

**Issue by TimHess** [vmware-tanzu/tanzu-toolkit-for-visual-studio#212]
When a manifest is selected, if services are listed, add validation to confirm the presence and/or status of services

eg: `cf service mydb`

**Comment by atwoosnam** [comment]
Only show services in the deployment dialog if they were provided in an imported manifest (i.e. don't provide an option to select services before a manifest import & don't allow the value to be changed after filled out by the manifest)

**Comment by zzori-theoriginal** [comment]
list the services, like how buildpacks are listed, and allow users to select or deselect any services that are listed

**Comment by atwoosnam** [comment]
For reference here's what happens on the command line when you try to push an app using a manifest that specifies services that don't exist on the CF:
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/1240e65d-4f65-4a63-b1e6-b26f5e9d6a35)

**Comment by atwoosnam** [comment]
And here is what the extension produces for a similar scenario:
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/62b0c8c8-7a16-47cc-b7c3-823e5b427ed7)

**Comment by atwoosnam** [comment]
Successfully pushed [this service-dependent `netcore3.1` app](https://github.com/SteeltoeOSS/Samples/tree/main/Management/src/CloudFoundry) using the command line:
- `dotnet publish -f netcoreapp3.1 -r win-x64`
- `cf push -f manifest-windows.yml -p bin/Debug/netcoreapp3.1/win-x64/publish`

Initially, the same app _failed_ to push `tanzu-toolkit-for-visual-studio` visx, but that was **because I didn't select the "Publish before pushing" option**.
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/8905d7c0-ddb2-429b-8d07-874781d1e293)

After selecting "Publish before pushing" (to properly mimic the command line flow), the app deployed successfully:
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/3039a445-796f-4c1c-b09e-8b84ba8ddb54)
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/211bb01b-07a0-4d9c-b455-b6270d7ae0f4)

This succeeded because the expected service ("`myMySqlService`") already existed in the target space ("`space-1-2`")
