### ISSUE TITLE
Trying to log into TAS in VS 2019 breaks

### ISSUE THREAD

**Issue by andrew-woosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#312]
Seems to be an issue with 2019 only (can't reproduce in 2022)
To reproduce:

1. log out of TAS if logged in
2. open deployment dialog
3. try signing into TAS via "Disconnected; click here" button

![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/9906dee9-8698-4dd4-bc10-6a1d63bbd47d)

## Update:

Trying to log into TAS from the TAS Explorer tool window in 2019 just crashes Visual Studio (no error)

**Comment by atwoosnam** [comment]
- Seems like this 2019/2022 VS crashing bug is most likely related to Community.VisualStudio.Toolkit (specifically the `toolkit:Themes.UseVsTheme="True"` line)
- This seems to have been fixed for v 17 of that nuget package: https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/issues/322
- Possible it may not have been fixed for v 16, which would explain why this bug is happening for VS 19 and not 22
- 

**TODO**:
- before fixing the bug, go through the views & find all usages of `toolkit:Themes.UseVsTheme="True"`
- for each usage:
  - check to see what the actual UX is
  - make sure VS doesn't crash
  - make sure any previously uncaught exceptions get logged
  - think about standardizing the response? (e.g. always/never give a pop-up error?)
- ... then see if there's a way to fix this bug
  - avoid using `toolkit:Themes.UseVsTheme="True"`?
  - ask Community.VisualStudio.Toolkit maintainers if there's an update for v 16?

**Comment by atwoosnam** [comment]
Identified 4 usages of `UseVsTheme` & started looking into the behavior when that line causes exception to be thrown. Both LoginView (opened via TasExplorer) and RemoteDebugView fail to open with no obvious feedback given to the user (error is logged in both cases).

Stopped looking into the remaining usages because I noticed that the exception about the missing `System.Text.Json` v6.0.0.0 assembly was still appearing -- these feel like separate issues

**Comment by atwoosnam** [comment]
Tried upgrading all NuGets & that resulted in the entire VSIX failing to load properly -- calls to `GetService` fail with exception:

```
Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.Extensions.Logging, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Users\awoosnam\AppData\Local\Microsoft\VisualStudio\16.0_f055835dExp\devenv.exe.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: The same bind was seen before, and was failed with hr = 0x80070002.
```

**Comment by atwoosnam** [comment]
App config file (`C:\Users\awoosnam\AppData\Local\Microsoft\VisualStudio\16.0_f055835dExp\devenv.exe.config`) had these entries:
```
<dependentAssembly>
				<assemblyIdentity name="Microsoft.Extensions.Logging" publicKeyToken="adb9793829ddae60" culture="neutral"/>
				<codeBase version="3.1.0.0" href="c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\windows.forms\Microsoft.Extensions.Logging.dll"/>
			</dependentAssembly>
...
<dependentAssembly>
				<assemblyIdentity name="System.Text.Json" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0"/>
				<codeBase version="4.0.1.0" href="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\System.Text.Json.dll"/>
			</dependentAssembly>
```

Machine configuration file (`C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config`) didn't mention either of those assemblies

**Comment by atwoosnam** [comment]
Still don't understand what component is expecting `System.Text.Json` v 6.0.0.0, but I got the error to go away by downgrading this NuGet package from 6.0.3 => 6.0.0 for both projects that use it (CfApiClient & Services)
