### ISSUE TITLE
Log whenever "ProprtyChanged" handler is null in AbstractViewModel

### ISSUE THREAD

**Issue by andrew-woosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#39]
The `RaisePropertyChangedEvent`  method on `AbstractViewModel` only raises an event if the "handler" property is not null. We've occasionally seen this property be null when running unit tests but it should never happen in the wild; if it does it's probably a good sign that we have a bug & we should log any relevant diagnostic info.

**Comment by atwoosnam** [comment]
Sounds like the handler value is `null` when there's no subscriber set up to listen for the event that's being raised & that's not necessarily a critical issue. 

Changing our code in `AbstractViewModel` to more closely follow this syntax (from [these MSFT docs](https://docs.microsoft.com/en-us/dotnet/standard/events/)), but otherwise not making any functional adjustments:
```
class Counter
{
    public event EventHandler ThresholdReached;

    protected virtual void OnThresholdReached(EventArgs e)
    {
        EventHandler handler = ThresholdReached;
        handler?.Invoke(this, e);
    }

    // provide remaining implementation for the class
}
```
