### ISSUE TITLE
Look and feel of the extension needs to match the Visual studio settings

### ISSUE THREAD

**Issue by jkonicki** [vmware-tanzu/tanzu-toolkit-for-visual-studio#65]

**Comment by atwoosnam** [comment]
I think we might be able to make our error popups look a little more "Visual Studio-y" with this snippet?
```
VsShellUtilities.ShowMessageBox(
    service_provider,
    insert_msg_here,
    insert_title_here,
    OLEMSGICON.OLEMSGICON_CRITICAL,
    OLEMSGBUTTON.OLEMSGBUTTON_OK,
    OLEMSGDEFBUTTON.OLEMSGDEFBUTTON_FIRST
);
```

https://github.com/vmware-tanzu/tanzu-toolkit-for-visual-studio/blob/b48de46167f09ef27bfa8a93397763ca9bc9cc13/TanzuForVS/Commands/PushToCloudFoundryCommand.cs#L124

**Comment by zzori-theoriginal** [comment]
Tasks :

- fix the look of the extension windows
- make the extension theme match the chosen theme of VS
- possibly take a look at the base colors of the extension

**Comment by zzori-theoriginal** [comment]
Found this snippet while researching more into matching the native theme with extensions....not so great haha

 [Here](https://newbedev.com/how-can-i-match-visual-studio-s-theme-when-creating-a-vsix-tool-window) is the full article

> feel as though the correct answer to this question is: you're not supposed to / Microsoft doesn't want you to do this. This post outlines the rationale behind this. The TLDR of the post seems to be that MS doesn't want third party windows looking like official VS windows, because it may cause confusion for users. I guess that's fair enough, but the flipside to that is that VS winds up looking pretty ugly with differently themed/styled windows.

> If - like me - you still want to push on and style your windows like VS, the best option seems to be to go with @Leo's post above and use EnvironmentColors. You won't get the styles but you can get pretty close with the colors at least. This is a good blog which outlines some more depth on this.

**Comment by zzori-theoriginal** [comment]
![VSerrorpopup.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/73719cfb-cddf-4618-8b4d-5255cb1b1995)

**Comment by zzori-theoriginal** [comment]
Blocked on being able to read the theme the user sets and apply it to the extension. Andrew and I paired for a full day trying to exhaust all options, but were unable to get it working. We have reached out to Dave and are awaiting a response

**Comment by jkonicki** [comment]
Blocker has been resolved.

**Comment by zzori-theoriginal** [comment]
This is how the extension currently looks; we're still implementing design changes
![extcomparisonwithinstance.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/1a0d10d7-37d7-4366-a183-8645914ef029)
![extxomparison.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/ff213aee-99be-4e87-8ec7-68b837473e1d)

**Comment by atwoosnam** [comment]
## CloudExplorerToolWindows in different themes:

- "Light"
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/2f8a3ce5-d4bc-468c-ab79-2815fef8d2ae)
- "Dark"
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/35db6b16-4aa7-4667-92bd-8057ffb4d2a3)
- "Blue"
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/c296fa7a-330e-4f8e-a479-d5663ec5148f)
- "Blue (Extra Contrast)"
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/e6b3bedd-d8a4-40ce-aa00-571f5ca44f1f)

**Comment by atwoosnam** [comment]
## Login Window in different themes:

#### "dark"
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/045294e5-1a5a-419b-9fc6-427a427525d0)
#### "light"
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/0c46e5a9-041d-4ae4-9376-5f951ecc6b20)
#### "blue"
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/0cad03cb-67c4-4a16-b644-72759b95c1b3)
#### "blue (extra contrast)"
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/98e86b6f-4239-4602-8f9e-9eeb5c82d7cd)
- _notice slightly different border colors between the pw box & the other input fields in this one (same happened with the "blue" theme); without any content or mouse-over, the borders for the top 3 fields are dark blue while the border for the pw box is light blue. Mousing over / clicking into the top 3 boxes creates a gold border while mousing over / clicking into the pw box creates a dark blue border._
  - _The difference is probably due to some special adjustments we had to make to the password box to get it to adopt the VS themes at all; with more fine-tuning I think we can get this box looking more consistent with the others_

**Comment by atwoosnam** [comment]
## Deployment Dialog in different themes:

#### "dark"
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/7ce89536-012e-4a8e-8c7d-601a3f29eeba)

**Comment by zzori-theoriginal** [comment]
![errorwhite.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/252b0997-64dd-484b-810e-b6daa8cb8be7)

We have left the `ErrorDialog` window white because it seems to be the standard for VS, in regards to their own error pop-ups. Waiting for team discussion before making changes on this one.
